version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - "4000:3000"
    networks:
      - my-network

  flask_app:
    build:
      context: .
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    command: python3 app.py && python3 pages/Calculate.py
    ports:
      - "8058:8058"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
